apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DATASOURCE_HOSTNAME: db-service # Este será el nombre del Service de la BD
  DATASOURCE_PORT: "3306"
  DATASOURCE_DB_NAME: articulosapi
